Refresh button pull request
CVC-DAG/dolores-tools pull request #1
Opened 2024-10-12 18:49 UTC by GerardAsbert

Els canvis importants estan a debug_tools/main.py i debug_tools/project_navigator_window.py. Diu que es pot fer merge automaticament sense cap problema, pero no em fio.

2024-10-14 08:46 UTC, ptorras commented
Està bé, però un parell de detalls!

- Si del main application necessites només les dades, no cal que passis tota la classe de MainApplication com a paràmetre, només l'objecte amb les dades que necessites. Pensa que és una referència mutable, aleshores pots anar modificant l'objecte. Així t'estalvies l'import circular i en general et fas la vida més fàcil..
- Si has de fer un import circular per temes de tipus, la forma idiomàtica és:
```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from on_necessitis import ElQueNecessitis
```
- El paràmetre a command suggereixo que cada part de la comanda la separis en un argument i ho passis com a llista. Fixa't com està fet amb la crida al Verovio per exemple. Si funciona així no cal que ho toquis, però pot estar bé.

2024-10-16 11:19 UTC, GerardAsbert commented
Creat classe FirebaseData i organitzat tot de forma que utilitzi aquesta classe, arreglat problema amb categoria 38. Si veus tot bé, ja es pot fer merge.

2024-10-17 08:54 UTC, ptorras requested changes
Quatre coses rapides, i ja estaria

2024-10-17 08:54 UTC, ptorras commented on debug_tool/firebase_data.py
> +        command = "gcloud storage cp -r gs://musicalignapp.appspot.com/uploads " + str(self.path)[:-7]
Separa els parametres de la comanda per si de cas. Hauria de ser una llista d'arguments. Les shells son poc agraïdes amb interpretar espais i si tens paths amb espais tindrà problemes.

2024-10-17 08:54 UTC, ptorras commented on debug_tool/firebase_data.py
> +from tkinter.filedialog import askdirectory
Import sense utilitzar.  Separacio de responsabilitats, no posis el dialeg a una classe que guarda info, posa'l a la classe de la interficie grafica.

2024-10-17 08:54 UTC, ptorras commented on debug_tool/firebase_data.py
> +        command = "gcloud storage cp -r gs://musicalignapp.appspot.com/uploads " + str(self.path)[:-7]
(mira com ho faig amb el Verovio)

2024-10-17 08:55 UTC, ptorras commented on debug_tool/firebase_data.py
> +from tkinter.filedialog import askdirectory
(la crida ja la fas a lloc, no pacha re, pero treu l'import)

2024-10-18 09:33 UTC, merged